Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /config.json
Not Found: /query
Invalid HTTP_HOST header: '/run/an.sock:'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/var/www/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/var/www/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/var/www/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '/run/an.sock:'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
Invalid HTTP_HOST header: '/run/an.sock:'. The domain name provided is not valid according to RFC 1034/1035.
Traceback (most recent call last):
  File "/var/www/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/var/www/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/var/www/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '/run/an.sock:'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
Not Found: /v2/_catalog
Not Found: /query
Not Found: /cgi-bin/authLogin.cgi
Not Found: /solr/admin/info/system
Not Found: /solr/admin/cores
